version: "3.5"
services:
  plex:
    container_name: plex
    hostname: plex
    restart: unless-stopped
    image: plexinc/pms-docker     # change this to plexinc/pms-docker:plexpass if you are a plexpass subscriber
    volumes:
      - ./mnt/plex:/config
      - ./mnt/plex-tmp:/transcode # Added this to keep image small
      - ./mnt/LPS:/data           # Changed this so you can add other libraries simply
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 32469:32469/udp
      - 1900:1900
      - 1900:1900/udp
      - 32410:32410
      - 32410:32410/udp
      - 32412:32412
      - 32412:32412/udp
      - 32413:32413
      - 32413:32413/udp
      - 32414:32414
      - 32414:32414/udp
    environment:
      - PLEX_UID=1000            # Make this the uid of your user account (type "id" in terminal and look for uid=xxxx)
      - PLEX_GID=1000            # Make this the gid of your user account (type "id" in terminal and look for gid=xxxx)
      - PLEX_CLAIM=${PLEX_CLAIM} # https://www.plex.tv/claim to get your claim token
