version: '3'
services:
  jelly:
    image: jellyfin/jellyfin
    restart: unless-stopped
    depends_on:
      - sonarr
      - radarr
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo 
    volumes:
      - ./config/jellyfin:/config
      - ./mnt/:/mnt/
    

  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - jackett
      - transmission
    ports:
      - 8989:8989
    environment:
    - PUID=1000
    - GUID=1000
    - TZ=America/Sao_Paulo
    volumes:
      - ./config/sonarr:/config
      - ./mnt/tv:/mnt/tv

  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - jackett
      - transmission
    ports:
      - 7878:7878
    environment:
    - PUID=1000
    - GUID=1000
    - TZ=America/Sao_Paulo
    volumes:
      - ./config/ronarr:/config
      - ./mnt/movies:/mnt/movies

  bazarr:
    image: linuxserver/bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/bazarr:/config
      - ./mnt/videos/movies:/mnt/videos/movies
      - ./mnt/videos/tv:/mnt/videos/tv
    # ports:
    #   - 6767:6767  # for debugging only

  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/transmission/config:/config
      - ./config/transmission/watch:/watch
      - ./mnt:/mnt
    ports:
      # - 9091:9091   # for debugging only
      - 51413:51413
      - 51413:51413/udp
  
  jackett:
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config/jackett:/config
    # ports:
    #   - 9117:9117  # for debugging only